---
abstract: 'check subroutine param types'
author:
  - 'Alex Alexandrov <swined@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attribute-Args
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: 0
  Test::Strict: 0
  YAML: 0
version: 0.04
